spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/timeattendancedb
    username: root
    password: "020623"
    type: com.alibaba.druid.pool.DruidDataSource
  mail:
    host: smtp.qq.com
    username: 1480371991@qq.com
    password: dttuygwdghgvbagc
    default-encoding: utf-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
    port: 465
    protocol: smtps
server:
  port: 8080